### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by ccpony** [devyumao/angular2-busy#44]
Appears so.

**Comment by techn1fire** [comment]
I used it a week ago, then it broke. I would love to see this work again. :(

**Comment by ccpony** [comment]
I've got it working.  What's the problem?

Sent from my Windows Phone
________________________________

**Comment by techn1fire** [comment]
I'm getting issues relating to #33

**Comment by ccpony** [comment]
And the solution suggested by dinusuresh  didn't work for you?  It did for me.  What errors are you getting?

**Comment by techn1fire** [comment]
Can you refer me to his solution

**Comment by ccpony** [comment]
He says in that thread:

@M4NC1O Sure. If you are looking to just get it working, then

In you package.json file make sure the angular2-busy dependency line is like this:
"angular2-busy": "https://github.com/dinusuresh/angular2-busy.git"

remove node_modules folder if you have it

npm cache clean
npm install

**Comment by KearneyLiu** [comment]
Has anyone upgraded to Angular 4.0.0? The animation module has been changed, which causes this library doesn't work. Could someone give me some hints?

**Comment by ccpony** [comment]
It would appear that this project has been abandoned.  Too bad.  It's a great concept.  Hopefully someone will pick it up.

**Comment by techn1fire** [comment]
Sorry for the late reply. I see what you are saying about making sure I have the package in the packages.json.
I followed the same steps I do with every plugin, install and save the package, then proceed with any other steps. However with this, it worked with the first machine I installed it on. Later I went to run a clone of my latest project build, with a npm_modules folder, and I get errors relating to issue #33

**Comment by ccpony** [comment]
Did you remember to npm --save the "angular2-dynamic-component" into your cloned project?

Anyway, for what it's worth, I've stripped ng2-busy out of my current project.  This repo is not being supported and it doesn't make sense to put this code into production.  More recent posts in this forum suggest that ng2-busy breaks under angular 4.

There seems to be every indication that this code is somewhat fragile.  Without support, that will just get worse.  It's just not worth it anymore.

**Comment by techn1fire** [comment]
I did that and this is what I get:

`Unhandled Promise rejection: Template parse errors:
Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>
            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">
            </DynamicComponent>
        </div>
"): BusyComponent@2:61 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError__zone_symbol__currentTask: ZoneTask__zone_symbol__error: Error: Template parse errors:
Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>
            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">
            </DynamicComponent>
        </div>
"): BusyComponent@2:61
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3260:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75714:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6058:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:21239:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:56089:68)
    at http://localhost:4200/vendor.bundle.js:55972:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55972:19)
    at createResult (http://localhost:4200/vendor.bundle.js:55854:19)
    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2602:26)
    at Zone.webpackJsonp.700.Zone.run (http://localhost:4200/polyfills.bundle.js:2394:43)
    at http://localhost:4200/polyfills.bundle.js:2981:57
    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2635:31)
    at Zone.webpackJsonp.700.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2434:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2814:35)message: "Template parse errors:↵Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>↵            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">↵            </DynamicComponent>↵        </div>↵"): BusyComponent@2:61"originalStack: "Error: Template parse errors:↵Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>↵            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">↵            </DynamicComponent>↵        </div>↵"): BusyComponent@2:61↵    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3260:33)↵    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75714:16)↵    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6058:16)↵    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:21239:19)↵    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:56089:68)↵    at http://localhost:4200/vendor.bundle.js:55972:62↵    at Set.forEach (native)↵    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55972:19)↵    at createResult (http://localhost:4200/vendor.bundle.js:55854:19)↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2602:26)↵    at Zone.webpackJsonp.700.Zone.run (http://localhost:4200/polyfills.bundle.js:2394:43)↵    at http://localhost:4200/polyfills.bundle.js:2981:57↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2635:31)↵    at Zone.webpackJsonp.700.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2434:47)↵    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2814:35)"stack: "Error: Template parse errors:↵Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>↵            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">↵            </DynamicComponent>↵        </div>↵"): BusyComponent@2:61↵    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3260:33)↵    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75714:16)↵    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6058:16)↵    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:21239:19)↵    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:56089:68)↵    at http://localhost:4200/vendor.bundle.js:55972:62↵    at Set.forEach (native)↵    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55972:19)↵    at createResult (http://localhost:4200/vendor.bundle.js:55854:19)↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2602:26)↵    at Zone.webpackJsonp.700.Zone.run (http://localhost:4200/polyfills.bundle.js:2394:43)↵    at http://localhost:4200/polyfills.bundle.js:2981:57↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2635:31)↵    at Zone.webpackJsonp.700.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2434:47)↵    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2814:35)"zoneAwareStack: "Error: Template parse errors:↵Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>↵            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">↵            </DynamicComponent>↵        </div>↵"): BusyComponent@2:61↵    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3260:33)↵    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75714:16)↵    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6058:16)↵    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:21239:19)↵    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:56089:68)↵    at http://localhost:4200/vendor.bundle.js:55972:62↵    at Set.forEach (native)↵    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55972:19)↵    at createResult (http://localhost:4200/vendor.bundle.js:55854:19)↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2602:26)↵    at Zone.webpackJsonp.700.Zone.run (http://localhost:4200/polyfills.bundle.js:2394:43)↵    at http://localhost:4200/polyfills.bundle.js:2981:57↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2635:31)↵    at Zone.webpackJsonp.700.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2434:47)↵    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2814:35)"__proto__: Object__zone_symbol__message: "Template parse errors:↵Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>↵            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">↵            </DynamicComponent>↵        </div>↵"): BusyComponent@2:61"__zone_symbol__stack: "Error: Template parse errors:↵Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>↵            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">↵            </DynamicComponent>↵        </div>↵"): BusyComponent@2:61↵    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3260:33)↵    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75714:16)↵    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6058:16)↵    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:21239:19)↵    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:56089:68)↵    at http://localhost:4200/vendor.bundle.js:55972:62↵    at Set.forEach (native)↵    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55972:19)↵    at createResult (http://localhost:4200/vendor.bundle.js:55854:19)↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2602:26)↵    at Zone.webpackJsonp.700.Zone.run (http://localhost:4200/polyfills.bundle.js:2394:43)↵    at http://localhost:4200/polyfills.bundle.js:2981:57↵    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2635:31)↵    at Zone.webpackJsonp.700.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2434:47)↵    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2814:35)"_nativeError: ZoneAwareErrormessage: (...)name: (...)originalStack: (...)stack: (...)toSource: ()toString: ()zoneAwareStack: (...)get message: ()set message: (value)get name: ()set name: (value)get originalStack: ()arguments: (...)caller: (...)length: 0name: "get"prototype: Object__proto__: ()[[FunctionLocation]]: zone.js:888[[Scopes]]: Scopes[5]set originalStack: (value)get stack: ()set stack: (value)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: BaseError Error: Template parse errors:
Can't bind to 'componentInputData' since it isn't a known property of 'DynamicComponent'. ("erClass" *ngIf="isActive()" @flyInOut>
            <DynamicComponent [componentTemplate]="template" [ERROR ->][componentInputData]="context">
            </DynamicComponent>
        </div>
"): BusyComponent@2:61
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3260:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:75714:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6058:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:21239:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:56089:68)
    at http://localhost:4200/vendor.bundle.js:55972:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:55972:19)
    at createResult (http://localhost:4200/vendor.bundle.js:55854:19)
    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:2602:26)
    at Zone.webpackJsonp.700.Zone.run (http://localhost:4200/polyfills.bundle.js:2394:43)
    at http://localhost:4200/polyfills.bundle.js:2981:57
    at ZoneDelegate.webpackJsonp.700.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:2635:31)
    at Zone.webpackJsonp.700.Zone.runTask (http://localhost:4200/polyfills.bundle.js:2434:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:2814:35)
consoleError @ zone.js:522
handleUnhandledRejection @ zone.js:527
_loop_1 @ zone.js:562
drainMicroTaskQueue @ zone.js:566
`

**Comment by devyumao** [comment]
Sorry for the late reply and I will keep the library updated :) Please update to the latest version.
#33 #39

**Comment by techn1fire** [comment]
I wouldn't close this topic until the issues referenced in it are solved.

**Comment by devyumao** [comment]
@nathanb1397 The issues are solved. You may try the latest version.
